### ISSUE TITLE
不支持1.19.3

### ISSUE THREAD

**Issue by a1544676809** [GregTaoo/Xibao-Plus-Plus#3]
如图，在minecraft1.19.3 fabric环境下安装该模组会启动失败。以下是错误报告
[crash-2022-12-09_20.40.14-client.txt](https://github.com/GregTaoo/Xibao-Plus-Plus/files/10194783/crash-2022-12-09_20.40.14-client.txt)

**Comment by GregTaoo** [comment]
收到

**Comment by GregTaoo** [comment]
已经支持
